---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a K8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
#        kubeconfig: /path/to/kubeconfigfile
    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: /Users/alfredamoah/GolandProjects/ansible-learn/k8s/nginx-config.yaml
        state: present
        namespace: my-app
