---
- name: Install node and npm
  hosts: 64.226.107.81
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  hosts: 64.226.107.81
  tasks:
    - name: Unpack the nodejs file
      ansible.builtin.unarchive:
        src: /Users/alfredamoah/IdeaProjects/simple-nodejs/nodejs-app-1.0.0.tgz
        dest: /root/
    - name: Install dependencies
      community.general.npm:
        path: /root/package
    - name: Start the application
      ansible.builtin.command:
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      ansible.builtin.shell: ps aux | grep node
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
